# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    rate_limiter:
        login_limiter:
            policy: sliding_window
            limit: 5  # Số lần đăng nhập tối đa
            interval: 1 minute  # Thời gian cho phép
            cache_pool: my_cache_pool  # Đảm bảo bạn có cache pool này
   

    # Note that the session will be started ONLY if you read or write from it.
    session:
            handler_id: null           # Sử dụng session mặc định
            gc_maxlifetime: 1440       # Thời gian sống của session (phút)
            name: MYSESSIONID          # Tên cookie session
            cookie_secure: auto        # Chỉ sử dụng cookie qua HTTPS
            cookie_httponly: true      # Ngăn chặn JavaScript truy cập vào cookie
            cookie_samesite: lax       # Cấu hình SameSite cho cookie
            cookie_lifetime: 3600     # Thời gian sống của cookie (trong giây)

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        # session:
        #     storage_factory_id: session.storage.factory.mock_file
        # config/packages/framework.yaml
      
