# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
   

    # Note that the session will be started ONLY if you read or write from it.
    session:
            handler_id: null           # Sử dụng session mặc định
            name: MYSESSIONID          # Tên cookie session
            cookie_secure: auto        # Chỉ sử dụng cookie qua HTTPS
            cookie_httponly: true      # Ngăn chặn JavaScript truy cập vào cookie
            cookie_samesite: lax       # Cấu hình SameSite cho cookie
            gc_maxlifetime: 1440       # Thời gian sống của session (phút)

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        # session:
        #     storage_factory_id: session.storage.factory.mock_file
        # config/packages/framework.yaml
      
