security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/login
            stateless: false    
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
                success_handler: App\Security\JsonLoginSuccessHandler
                failure_handler: App\Security\JsonLoginFailureHandler

        register:
            pattern: ^/api/register
            stateless: true
            security: false  # Không yêu cầu bảo mật cho đăng ký
        # logout:
        #         pattern: ^/api/logout
        #         stateless: true
        #         security: false
        #         invalidate_session: true
                
    #router nào để vào fireware thì sẽ có authenticated
        main:
            pattern: ^/api/security
            stateless: false
            lazy: true
            provider: app_user_provider
          
            # form_login:
            #     check_path: /api/login
            #     login_path: /api/login
            #     username_parameter: email
            #     password_parameter: password
            #     enable_csrf: true
            #     csrf_parameter: _csrf_token
            #     success_handler: App\Security\JsonLoginSuccessHandler
            #     failure_handler: App\Security\JsonLoginFailureHandler
            
            

    access_control:
        - { path: ^/api/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/questions-sql, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/answer, roles: ROLE_USER }
        - { path: ^/api/category, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }  

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
