security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/login
            stateless: false    
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
                success_handler: App\Security\JsonLoginSuccessHandler
                failure_handler: App\Security\JsonLoginFailureHandler
            login_throttling:
                   max_attempts: 3 
                   interval: '10 minutes'
        register:
            pattern: ^/api/register
            stateless: false
            security: false  # Không yêu cầu bảo mật cho đăng ký

        main:
            pattern: ^/api/security
            stateless: false
            lazy: true
            provider: app_user_provider

    access_control:
        - { path: ^/api/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/questions-sql, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/answer, roles: ROLE_USER }
        - { path: ^/api/category, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }  

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
