# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\EventListener\ExceptionListener:
        tags: [kernel.event_listener]
    App\EventSubscriber\ExceptionSubscriber:
        tags: [kernel.event_listener]
    App\EventListener\MyMultiListener:
        tags:
            # - { name: kernel.event_listener, event: 'foo', method: 'onFoo' }
            - { name: kernel.event_listener, event: kernel.request, method: onFoo }
            - { name: kernel.event_listener, event: 'bar', method: 'onBarEvent' }
            - { name: kernel.event_listener, event: CustomEvent::class, method: 'onCustomEvent' }
    App\Security\JsonLoginSuccessHandler:
        arguments:
            $logger: '@logger'
    App\Controller\EventController:
        tags: ['controller.service_arguments']
    App\Security\JwtAuthenticationService:
        arguments:
            $jwtManager: '@lexik_jwt_authentication.jwt_manager'
            $tokenStorage: '@security.token_storage'
            $userProvider: '@security.user.provider.concrete.app_user_provider' # 'app_user_provider' la2 tên provider của bạn
    Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
        arguments:
            - '%env(DATABASE_URL)%'
            # - { db_table: 'sessions', db_id_col: 'id',db_data_col: 'sessions_data',db_time_col: 'sessions_time',db_lifetime_col: 'sessions_lifetime'}
            - { db_table: 'sessions'} #thay the cau hinh mac dinh db_connection_options thanh2 session_ip

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
